### PR TITLE
Feature/python main

### PR DESCRIPTION
**Pull request by paloblanco**
Hi! I love this repo, just started using it to maintain my resume. I am a windows user, however, so I needed to create a python script in lieu of the makefile to glue all the functionality together. I hope you will consider pulling this in so that other windows users can take advantage of commandline functionality. Thanks!!

-Rocco

### CODE REVIEW

**Comment by mikepqr** [comment]
Hi @paloblanco, sorry for the slow reply. I hadn't given much thought to Windows support, so thank you very much for highlighting the missing `make` issue (and the more complicated weasyprint situation on Windows). I will give this some thought and get back to you.

**Comment by mikepqr** [comment]
I wrote a shorter version of your python script to handle building the HTML. This is a less general and less robust than yoyur script, but is no worse than the previous Makefile, so I think I prefer this simpler approach for now.

I'm going to leave this issue open while I look more closely at weasyprint. Thanks again!

**Comment by paloblanco** [comment]
I think your solution is perfectly fine. It just allows windows users to use it now, or allows it to be worked into a python workflow, for instance if someone is generating a static site in python.

Unfortunately, there is now easy way for windows users to just "pip install" weasyprint - I think this is the nature of the beast. I had included some notes in the readme about how a user could just open the resume in their browser and print.

**Comment by mikepqr** [comment]
Yup. See #1 for what will probably end up being the recommended solution for non-unix systems.

**Comment by mikepqr** [comment]
@paloblanco do you have time to test the [chrome branch](https://github.com/mikepqr/resume.md/tree/chrome)?

It removes the weasyprint dependency entirely. I would be very grateful for feedback from a Windows user! Please let me know if anything is broken for you, or if the revised README is unclear.

**Comment by paloblanco** [comment]
I wrote up an issue - the chrome branch fails on windows, and the error code is not super helpful. Sorry for the delay in testing. Issue is here: https://github.com/mikepqr/resume.md/issues/14

**Pull request closed without merging**
