### PR TITLE
add --no-sandbox parameter to Chromium

### PR DESCRIPTION
**Pull request by oupala**

### CODE REVIEW

**Comment by mikepqr** [comment]
Why? Please write a meaningful commit message.

**Comment by oupala** [comment]
When running resume.md with GitLab CI, the process is running inside a container, and hence Chromium require a specific configuration in order to run as a headless browser. The process is also often running as root and this has a specific issue:

```
# python3 resume.py
Wrote /lab/resume.html
Found Chrome or Chromium at /usr/bin/google-chrome
[0715/191521.895591:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

It is hence a common workaround to run Chromium with `--no-sandbox`.

**Comment by mikepqr** [comment]
Fair enough! Please say that in the commit message and I'll be happy to land this,

**Comment by oupala** [comment]
I've edited the commit message. I have not found how to do this using GitHub web interface, I had to use my terminal...

**Comment by mikepqr** [comment]
Thanks!

**Pull request merged**
